kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: spring-app-dc
  namespace: demo
spec:
  strategy:
    type: Rolling
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - spring-app
        from:
          kind: ImageStreamTag
          namespace: demo
          name: 'spring-app:latest'
  replicas: 1
  template:
    metadata:
      labels:
        deployment-config.name: triggeer-dc
    spec:
      containers:
        - name: spring-app
          image: >-
            image-registry.openshift-image-registry.svc:5000/demo/spring-app
          ports:
            - containerPort: 9080
              protocol: "TCP"
          imagePullPolicy: Always
