apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-liberty
  name: spring-liberty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-liberty
  template:
    metadata:
      labels:
        app: spring-liberty
    spec:
      containers:
        - name: spring-liberty
          image: gooner4life/spring-liberty:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
          env:
          - name: app.version
            valueFrom:
              configMapKeyRef:
                name: spring-liberty-cm
                key: app.version
          - name: db.password
            valueFrom:
              secretKeyRef:
                name: db-password-secret
                key: password
